/* @(#)limits.h	1.1 2/23/90 1 */

/* Integral limits  */

#define	CHAR_BIT	8
#define	SCHAR_MIN	-128
#define	SCHAR_MAX	127
#define	UCHAR_MAX	255u
#define	CHAR_MIN	SCHAR_MIN
#define	CHAR_MAX	SCHAR_MAX
#define	MB_LEN_MAX	1
#define	SHRT_MIN	-32768
#define	SHRT_MAX	32767
#define	USHRT_MAX	(unsigned)65535
#define	INT_MIN		-32768
#define	INT_MAX		32767
#define	UINT_MAX	(unsigned)65535
#define	LONG_MIN	(long)-2147483648
#define	LONG_MAX	(long)2147483647
#define	ULONG_MAX	(unsigned long)4294967295
